ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp

onlyBuiltDependencies:
  - puppeteer

patchedDependencies:
  '@nuxt/devalue': patches/@nuxt__devalue.patch
  vue-loader: patches/vue-loader.patch

overrides:
  "@types/express": "^4"
  "@types/node": "^24"
  "express": "^4"
