name: Generate README

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - .vscode
      - .editorconfig
      - .gitignore

concurrency:
  group: generate-readme
  cancel-in-progress: true

env:
  README_DIR: trinovantes

jobs:
  generate-readme:
    name: Generate README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout trinovantes-src repo
        uses: actions/checkout@v4

      - name: Checkout trinovantes repo
        uses: actions/checkout@v4
        with:
          repository: Trinovantes/trinovantes
          token: ${{ secrets.GH_PAT }}
          path: ${{ env.README_DIR }}

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Set up bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run
        run: yarn generateReadme

      - name: Move readme to dir
        run: |
          mv README.md ${{ env.README_DIR }}

      - name: Commit worktree branch
        working-directory: ${{ env.README_DIR }}
        run: |
          git config --global user.name 'Generate README Workflow'
          git config --global user.email '<>'
          git add README.md
          git commit -m "Generate README $(date -u)" || true
          git push
