name: Generate README

on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths-ignore:
      - README.md
      - .vscode
      - .editorconfig
      - .gitignore

env:
  BUILD_DIR: dist
  WORKTREE_DIR: master

jobs:
  generate-readme:
    name: Generate README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn buildReadme

      - name: Run
        run: yarn generateReadme

      - name: Set up worktree
        run: |
          git fetch
          git worktree add $WORKTREE_DIR master
          find $WORKTREE_DIR -not -path $WORKTREE_DIR -not -path '*/\.*' | xargs -t rm -rf
          mv README.md $WORKTREE_DIR

      - name: Commit worktree branch
        working-directory: ${{ env.WORKTREE_DIR }}
        run: |
          git config --global user.name 'Generate README Workflow'
          git config --global user.email '<>'
          git add README.md
          git commit -m "Generate README $(date -u)" || true
          git push
