name: Update README

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - .vscode
      - .editorconfig
      - .gitignore

jobs:
  updateReadme:
    name: Update README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          CACHE_NAME: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ hashFiles('**/yarn.lock', '**/package-lock.json') }}

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn buildReadme

      - name: Run
        run: yarn startReadme

      - name: Commit changes
        run: |
          git config --global user.name 'Update README Workflow'
          git config --global user.email '<>'
          git add README.md
          git commit -m "Update README $(date -u)" || true
          git push
